name: hospitel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.13
  geolocator: ^5.1.5
  permission_handler: ^3.0.1
  google_maps_flutter: ^0.5.19
  flutter_spinkit: ^5.1.0
  simple_animations: ^1.3.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: Opun
        fonts:
          - asset: assets/fonts/Opun-Regular.ttf
  uses-material-design: true

  assets:
    - assets/images/
